{
    name: release + npm,
    on: { push: { tags: ['v*'] } },
    jobs:
        {
            build:
                { runs-on: ubuntu-latest, steps: [
                            {
                                uses: actions/checkout@v2,
                            },
                            {
                                name: 'read .nvmrc',
                                run: 'echo "##[set-output name=NVMRC;]$(cat .nvmrc)"',
                                id: nvm,
                            },

                            {
                                uses: actions/setup-node@v2,
                                with:
                                    {
                                        node-version: '${{ steps.nvm.outputs.NVMRC }}',
                                        registry-url: 'https://registry.npmjs.org',
                                        scope: '@nuggxyz',
                                    },
                            },
                            { run: yarn },
                            { run: yarn package },
                            {
                                run: 'yarn npm publish --access public --otp ${{ secrets.NPM_AUTOMATION_KEY }}',
                                # env:
                                #     {
                                #         NODE_AUTH_TOKEN: '',
                                #     },
                            },
                            {
                                uses: marvinpinto/action-automatic-releases@latest,
                                with:
                                    {
                                        repo_token: '${{ secrets.GITHUB_TOKEN }}',
                                        prerelease: true,
                                    },
                            },
                        ] },
        },
}
