/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDotNuggHolder,
  IDotNuggHolderInterface,
} from "./IDotNuggHolder";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[][]",
        name: "items",
        type: "uint256[][]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "dotNuggUpload",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDotNuggHolder__factory {
  static readonly abi = _abi;
  static createInterface(): IDotNuggHolderInterface {
    return new utils.Interface(_abi) as IDotNuggHolderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDotNuggHolder {
    return new Contract(address, _abi, signerOrProvider) as IDotNuggHolder;
  }
}
